image: "python:3.9-alpine"

"🏗️ Python wheel":
  stage: build
  before_script:
    - python -m pip install --upgrade pip build twine
  script:
    - python -m build
    - twine check dist/*

"🔍 Python code format":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install .
    - pip install .[test]
  script:
    - flake8 ir_axioms/ tests/ examples/

"🔍 Python Lint":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install .
    - pip install .[test]
  script:
    - pylint -E ir_axioms tests.unit examples --ignore-paths=^ir_axioms.backend

"🔍 Python Lint backend":
  stage: test
  parallel:
    matrix:
      - backend:
          - pyserini
          - pyterrier
  before_script:
    - apk --no-cache add openjdk11 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
    - python -m pip install --upgrade pip
    - pip install .
    - pip install .[test]
    - pip install .[${backend}]
  script:
    - pylint -E ir_axioms.backend.${backend} tests.integration.${backend}

"🧪 Python unit tests":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install .
    - pip install .[test]
  script:
    - pytest ir_axioms/ tests/unit/ examples/ --ignore=ir_axioms/backend/

"🧪 Python integration tests":
  stage: test
  parallel:
    matrix:
      - backend:
          - pyserini
          - pyterrier
  before_script:
    - apk --no-cache add openjdk11 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
    - python -m pip install --upgrade pip
    - pip install .
    - pip install .[test]
    - pip install .[${backend}]
  script:
    - pytest tests/integration/${backend}/
