image: "python:3.9"

"🏗️ Python wheel":
  stage: build
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel
    - pip install -e .
  script:
    - python -m build

"🔍 Python code format":
  stage: test
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel
    - pip install -e .
    - pip install -e .[test]
  script:
    - flake8

"🔍 Python Lint":
  stage: test
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel
    - pip install -e .
    - pip install -e .[test]
  script:
    - pylint -E ir_axioms

"🧪 Python unit tests":
  stage: test
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel
    - pip install -e .
    - pip install -e .[test]
  script:
    - pytest --ignore=tests/integration/

"🧪 Python integration tests":
  parallel:
    matrix:
      - backend: pyserini
        package: pyserini
      - backend: pyterrier
        package: python-terrier
  stage: test
  before_script:
    - python -m pip install --upgrade pip build setuptools wheel
    - pip install -e .
    - pip install -e .[test]
    - pip install ${package}
  script:
    - pytest tests/integration/test_${backend}.py
