image: "python:3.8"

before_script:
  - python --version
  - pip install .[test]
  - pip install .[pyserini]
  - pip install .[pyterrier]

stages:
  - "Static Analysis"
  - "Test"

"🧪 Code format":
  stage: "Static Analysis"
  script:
    - flake8

"🧪 Lint":
  stage: "Static Analysis"
  script:
    - pylint -E ir_axioms

"🧪 Test":
  stage: "Test"
  script:
    - pytest --cov --cov-report=term --cov-report=xml || true
