image: "python:3.9"

"🏗️ Python wheel":
  stage: build
  before_script:
    - python -m pip install --upgrade pip build twine
    - pip install -e .
  script:
    - python -m build
    - twine check dist/*

"🔍 Python code format":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install -e .[test]
  script:
    - flake8 ir_axioms tests examples

"🔍 Python Lint":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install -e .[test]
  script:
    - pylint -E ir_axioms tests examples

"🔍 Python Lint backend":
  stage: test
  parallel:
    matrix:
      - backend: pyserini
        package: pyserini
      - backend: pyterrier
        package: python-terrier
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install -e .[test]
    - pip install ${package}
  script:
    - pylint -E ir_axioms/backend/${backend}/ tests/integration/${backend}/

"🧪 Python unit tests":
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install -e .[test]
  script:
    - pytest ir_axioms --ignore=ir_axioms/backend/ tests --ignore=tests/integration/ examples

"🧪 Python integration tests":
  stage: test
  parallel:
    matrix:
      - backend: pyserini
        package: pyserini
      - backend: pyterrier
        package: python-terrier
  before_script:
    - python -m pip install --upgrade pip
    - pip install -e .
    - pip install -e .[test]
    - pip install ${package}
  script:
    - pytest tests/integration/${backend}/
