[build-system]
requires = ["setuptools>=50", "wheel", "setuptools-declarative-requirements"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_cli = "True"
filterwarnings = [
    'ignore::DeprecationWarning',
]