name: CI

on:
  push:

jobs:
  test-python:
    name: "🧪 Test Python code"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - 3.7
          - 3.8
          - 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: "🧰 Install dependencies"
        run: pip install .[test]
      - name: "🧪 Check Python code format"
        run: flake8
      - name: "🧪 Lint Python code"
        run: pylint -E ir_axioms
      - name: "🧪 Test Python code"
        run: pytest --cov --cov-report=term --cov-report=xml || true
      - name: "📤 Upload test coverage"
        uses: actions/upload-artifact@v2
        with:
          path: coverage.xml
          name: Python test coverage
      - name: "📤 Publish test coverage"
        uses: codecov/codecov-action@v1